[tool.poetry]
name = "llmsat"
version = "0.1.0"
description = "An LLM-based autonomous agent for space exploration"
authors = ["David Maranto <D.Maranto1122@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
agi-stk12 = {path = "agi.stk12-12.6.0-py3-none-any.whl"}
langchain = "^0.0.278"
openai = "^0.27.10"
python-decouple = "^3.8"
pydantic = "^2.3.0"
pytest = "^7.4.1"
astropy = "^5.3.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
